# 程序名配置
app.name=[heart.spring]

# knife4j 安全密码登录配置
server.port=8081
knife4j.enable=true
knife4j.basic.enable=true
knife4j.basic.username=admin
knife4j.basic.password=admin
knife4j.setting.language=zh-CN