# 程序名配置
app.name=[heart.spring]

# knife4j 安全密码登录配置
server.port=8081
knife4j.enable=true
knife4j.basic.enable=true
knife4j.basic.username=admin
knife4j.basic.password=admin
knife4j.setting.language=zh-CN

# 引入自定义job配置 application-custom.properties
spring.profiles.include=custom
# 是否启用Quartz
spring.quartz.enabled=true
# 定义线程池大小
spring.quartz.properties.org.quartz.threadPool.threadCount=10
# 定义调度器名称
spring.quartz.properties.org.quartz.scheduler.instanceName=MyQuartzScheduler
# 是否覆盖已存在的任务 当新的任务定义与已存在的任务冲突时，Quartz会根据此配置决定是否覆盖旧的任务。在开发过程中，建议设置为true，以避免任务冲突
spring.quartz.overwrite-existing-jobs=true
# 是否自动启动
spring.quartz.auto-startup=true
# 数据库存储配置（可选，用于集群支持）
#spring.quartz.properties.org.quartz.jobStore.class=org.quartz.impl.jdbcjobstore.JobStoreTX
#spring.quartz.properties.org.quartz.jobStore.driverDelegateClass=org.quartz.impl.jdbcjobstore.StdJDBCDelegate
#spring.quartz.properties.org.quartz.jobStore.dataSource=myDS
#spring.quartz.properties.org.quartz.dataSource.myDS.driver=com.mysql.cj.jdbc.Driver
#spring.quartz.properties.org.quartz.dataSource.myDS.URL=jdbc:mysql://localhost:3306/quartz_db
#spring.quartz.properties.org.quartz.dataSource.myDS.user=root
#spring.quartz.properties.org.quartz.dataSource.myDS.password=your_password
